# Generated by Django 5.0.6 on 2024-06-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
